### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by xavikortes** [CodelyTV/eslint-config-codely#3]
Hola codeliers, lo primero, gran trabajo como siempre.

He estado probando la configuración y con las siguientes versiones:

```json
{
    "eslint": "^8.25.0",
    "eslint-config-codely": "^2.0.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-hexagonal-architecture": "^1.0.3",
    "prettier": "^2.7.1"
}
```

y configuración de .eslintrc.js con typescript:

```js
{
  extends: [ "eslint-config-codely/typescript" ],
  parserOptions: {
    project: ["./tsconfig.json"],
  },
}
```

Al lanzar "npx eslint ." en mi proyecto, me salta este error:

```
  0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
  The file does not match your project config: .eslintrc.js.
  The file must be included in at least one of the projects provided
```

He comprobado que el error se soluciona al aplicar el parserOptions solamente a los ficheros "ts":

```js
{
  extends: [ "eslint-config-codely/typescript" ],
  overrides: [
    {
      files: ["**/*.ts"],
      parserOptions: {
        project: ["./tsconfig.json"],
      },
    }
  ]
}
```
No tengo claro si es un error de algunas versiones o que está pasando, pero esto me funcionó a mi. Por si a alguien le ayuda o se quiere actualizar en el README.md

**Comment by JavierCane** [comment]
Gracias por el report!

Le echamos un ojo ASAP 🙏

**Comment by nuria-fl** [comment]
Hola!

Toda la razón, si en el repositorio tenemos archivos `.js` es mejor añadir el `parserOptions` en overrides para que sólo afecte a ficheros TypeScript. Hay otras opciones como ignorar los archivos js desde tsconfig.json, pero es más simple con lo que comentas.

Actualizamos el readme y disculpa la demora 🙌
