### ISSUE TITLE
Error in configuration

### ISSUE THREAD

**Issue by fjmn2001** [CodelyTV/eslint-config-codely#5]
Hello, when I am doing CI, it fails with the following error

![image](https://user-images.githubusercontent.com/499499/206580465-0f47ee3f-6511-45af-9cec-3431a220c027.png)

**Comment by francoborgiani** [comment]
Hi, I'm having the same issue and I didn't found a solution for it. 

Please, can you let me know if you solve the problem?

**Comment by nuria-fl** [comment]
Hi! We have fixed this in version 2.1.1.
It was caused by a breaking change introduced in a minor version of typescript/eslint: https://github.com/typescript-eslint/typescript-eslint/issues/6132

Thanks for the report!
